# Generated by Django 6.1.1 on 2026-09-11 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutputDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='label สำหรับแสดงผล (default = browser label)', max_length=255)),
                ('device_id', models.CharField(help_text='deviceId จาก enumerateDevices()', max_length=255)),
                ('platform', models.CharField(choices=[('windows', 'Windows'), ('macos', 'macOS'), ('linux', 'Linux'), ('other', 'Other')], default='other', max_length=32)),
                ('is_active', models.BooleanField(default=True, help_text='เปิด/ปิดการใช้งานใน dropdown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Output Device',
                'verbose_name_plural': 'Output Devices',
                'ordering': ['-is_active', 'name'],
                'constraints': [models.UniqueConstraint(fields=('platform', 'device_id'), name='uniq_output_device_platform_device')],
            },
        ),
        migrations.CreateModel(
            name='OutputDeviceSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id_legacy', models.CharField(blank=True, default='', help_text='snapshot ของ device ID (กันกรณี device ถูกลบ)', max_length=255)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='auto_capture', help_text='ที่มาของการเลือก เช่น auto_capture', max_length=32)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selections', to='output_devices.outputdevice')),
            ],
            options={
                'verbose_name': 'Output Device Selection',
                'verbose_name_plural': 'Output Device Selections',
                'ordering': ['-selected_at'],
            },
        ),
    ]
