# Generated by Django 5.2.17 on 2026-09-11 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('output_devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outputdeviceselection',
            options={'ordering': ['-selected_at', '-id'], 'verbose_name': 'Output Device Selection', 'verbose_name_plural': 'Output Device Selections'},
        ),
    ]
