# Generated by Django 6.1.1 on 2026-09-05 14:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0016_remove_chatmessage_core_chatme_charact_071bea_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeLiveChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_id', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('stopped', 'Stopped')], default='active', max_length=20)),
                ('auto_reply', models.BooleanField(default=False)),
                ('messages_received', models.IntegerField(default=0)),
                ('replies_sent', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yt_sessions', to='core.character')),
            ],
            options={
                'db_table': 'core_youtubelivechatsession',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='YouTubeChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=200)),
                ('author_channel_id', models.CharField(blank=True, max_length=100)),
                ('text', models.TextField()),
                ('is_mod', models.BooleanField(default=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('is_super_chat', models.BooleanField(default=False)),
                ('ai_response', models.TextField(blank=True)),
                ('ai_responded', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat_messages.youtubelivechatsession')),
            ],
            options={
                'db_table': 'core_youtubechatmessage',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('user_name', models.CharField(blank=True, default='', help_text='Name of the user who sent this message (for per-user memory)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.character')),
            ],
            options={
                'db_table': 'core_chatmessage',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['character', 'user_name', 'created_at'], name='core_chatme_charact_071bea_idx')],
            },
        ),
    ]
