# Generated by Django 6.1.1 on 2026-09-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VTubeStudioSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.CharField(default='ws://0.0.0.0:9000', help_text='WebSocket URL สำหรับเชื่อมต่อ VTube Studio API (เช่น ws://0.0.0.0:9000)', max_length=255)),
                ('port', models.IntegerField(default=9000, help_text='Port สำหรับ VTube Studio API')),
                ('is_connected', models.BooleanField(default=False, help_text='สถานะการเชื่อมต่อ (อัปเดตอัตโนมัติเมื่อทดสอบการเชื่อมต่อ)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'VTube Studio Settings',
                'verbose_name_plural': 'VTube Studio Settings',
            },
        ),
    ]
