# Generated by Django 6.1.1 on 2026-09-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtube_studio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vtubestudiosettings',
            name='api_url',
            field=models.CharField(default='ws://127.0.0.1:9000', help_text='WebSocket URL สำหรับเชื่อมต่อ VTube Studio API (เช่น ws://127.0.0.1:9000)', max_length=255),
        ),
    ]
