# Generated by Django 6.1.1 on 2026-09-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtube_studio', '0002_alter_vtubestudiosettings_api_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vtubestudiosettings',
            name='api_url',
            field=models.CharField(default='ws://192.168.1.10:9000', help_text='WebSocket URL สำหรับเชื่อมต่อ VTube Studio API (เช่น ws://192.168.1.10:9000)', max_length=255),
        ),
    ]
