# Generated by Django 6.1.1 on 2026-09-05 14:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Free LLM API', max_length=100)),
                ('api_url', models.URLField(default='http://127.0.0.1:31415/v1/chat/completions')),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('model_name', models.CharField(default='auto', max_length=100)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=2048)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM Provider',
                'verbose_name_plural': 'LLM Providers',
                'db_table': 'core_llmprovider',
                'ordering': ['-created_at'],
            },
        ),
    ]
