# Generated by Django 6.1.1 on 2026-09-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmprovider',
            name='api_url',
            field=models.URLField(default='http://192.168.1.10:31415/v1/chat/completions'),
        ),
    ]
