# Generated by Django 6.1.1 on 2026-09-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_alter_llmprovider_api_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmprovider',
            name='api_url',
            field=models.URLField(default='http://192.168.1.10:9001/v1/chat/completions'),
        ),
    ]
