# Generated by Django 6.1.1 on 2026-09-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TTSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questioner_enabled', models.BooleanField(default=True, help_text='เล่นเสียง TTS สำหรับผู้ส่งแชท (ผู้ถาม)')),
                ('questioner_voice', models.CharField(default='th-TH-PremwadeeNeural', help_text='เสียง TTS สำหรับผู้ถาม', max_length=100)),
                ('questioner_rate', models.CharField(default='+0%', help_text='ความเร็วเสียงผู้ถาม (เช่น +10%, -10%)', max_length=10)),
                ('questioner_say_username', models.BooleanField(default=True, help_text='พูดชื่อผู้ใช้ก่อนข้อความ (เช่น username... รอ 3 วินาที... ข้อความ)')),
                ('responder_enabled', models.BooleanField(default=True, help_text='เล่นเสียง TTS สำหรับผู้ตอบ (Character)')),
                ('responder_voice', models.CharField(default='th-TH-PremwadeeNeural', help_text='เสียง TTS สำหรับผู้ตอบ', max_length=100)),
                ('responder_rate', models.CharField(default='+0%', help_text='ความเร็วเสียงผู้ตอบ', max_length=10)),
                ('responder_delay_ms', models.IntegerField(default=3000, help_text='เวลารอระหว่างชื่อผู้ใช้กับข้อความ (มิลลิวินาที)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TTS Settings',
                'verbose_name_plural': 'TTS Settings',
                'db_table': 'core_ttssettings',
            },
        ),
    ]
