# Generated by Django 5.2.17 on 2026-09-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_tts', '0003_set_delay_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttssettings',
            name='output_device_id',
            field=models.CharField(blank=True, default='', help_text="Web Audio device ID สำหรับเล่น TTS (เช่น 'default', 'communications', หรือ device ID จาก enumerateDevices). ว่างไว้ = browser default speaker.", max_length=255),
        ),
    ]
