# Generated by Django 6.1.1 on 2026-09-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_tts', '0005_copy_output_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttssettings',
            name='questioner_voice',
            field=models.CharField(default='th_TH-tsync2-medium', help_text='เสียง TTS สำหรับผู้ถาม', max_length=100),
        ),
        migrations.AlterField(
            model_name='ttssettings',
            name='responder_voice',
            field=models.CharField(default='th_TH-tsync2-medium', help_text='เสียง TTS สำหรับผู้ตอบ', max_length=100),
        ),
    ]
