# Generated by Django 6.1.1 on 2026-09-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='llmprovider',
            options={'ordering': ['-created_at'], 'verbose_name': 'LLM Provider', 'verbose_name_plural': 'LLM Providers'},
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='model_name',
            field=models.CharField(default='auto', max_length=100),
        ),
    ]
