# Generated by Django 5.2.16 on 2026-09-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_llmprovider_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='response_language',
            field=models.CharField(default='thai', help_text='Language the character should always respond in (e.g., thai, english, japanese)', max_length=20),
        ),
    ]
