# Generated by Django 5.2.17 on 2026-09-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_youtubelivechatsession_youtubechatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='user_name',
            field=models.CharField(blank=True, default='', help_text='Name of the user who sent this message (for per-user memory)', max_length=100),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['character', 'user_name', 'created_at'], name='core_chatme_charact_071bea_idx'),
        ),
    ]
