# Generated by Django 5.2.17 on 2026-09-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chatmessage_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='enable_per_user_memory',
            field=models.BooleanField(default=True, help_text='Enable per-user memory (remember individual users by name)'),
        ),
        migrations.AddField(
            model_name='character',
            name='memory_duration_days',
            field=models.IntegerField(default=3, help_text='How long to remember user messages (days)'),
        ),
        migrations.AddField(
            model_name='character',
            name='memory_max_messages',
            field=models.IntegerField(default=20, help_text='Maximum number of messages to include in context per user'),
        ),
    ]
