# Generated by Django 5.2.17 on 2026-09-04 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_character_enable_per_user_memory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='memory_max_messages',
        ),
    ]
