# Generated by Django 5.2.17 on 2026-09-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_character_memory_max_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='system_prompt_ai',
            field=models.TextField(blank=True, help_text='AI-generated prompt based on chat history — combined with system prompt during chat'),
        ),
    ]
