# Generated by Django 5.2.17 on 2026-09-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_character_system_prompt_ai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='system_prompt_ai',
            field=models.TextField(blank=True, help_text='AI-generated prompt based on chat history (max 8000 chars) — combined with system prompt during chat', max_length=8000),
        ),
    ]
