# Generated by Django 5.2.17 on 2026-09-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_character_system_prompt_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='name_en',
            field=models.CharField(blank=True, help_text='ชื่อภาษาอังกฤษ (เช่น Mena)', max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='name_th',
            field=models.CharField(blank=True, help_text='ชื่อภาษาไทย (เช่น มีนา)', max_length=100),
        ),
    ]
