# Generated by Django 5.2.17 on 2026-09-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_character_name_en_character_name_th'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='response_length',
            field=models.CharField(choices=[('short', 'สั้น (Short)'), ('normal', 'ปกติ (Normal)'), ('long', 'ยาว (Long)'), ('custom', 'Custom')], default='short', help_text='ความยาวคำตอบ: สั้น=1-2 ประโยค, ปกติ=2-3 ประโยค, ยาว=เต็มที่, custom=ตั้งค่าเอง', max_length=10),
        ),
    ]
