# Generated by Django 5.2.17 on 2026-09-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_character_response_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='custom_max_tokens',
            field=models.IntegerField(blank=True, help_text='Custom max_tokens (ใช้เมื่อเลือก Custom)', null=True),
        ),
    ]
