# Generated by Django 5.2.17 on 2026-09-04 18:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_character_custom_max_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questioner_enabled', models.BooleanField(default=True, help_text='เล่นเสียง TTS สำหรับผู้ส่งแชท (ผู้ถาม)')),
                ('questioner_voice', models.CharField(default='th-TH-PremwadeeNeural', help_text='เสียง TTS สำหรับผู้ถาม', max_length=100)),
                ('questioner_rate', models.CharField(default='+0%', help_text='ความเร็วเสียงผู้ถาม (เช่น +10%, -10%)', max_length=10)),
                ('questioner_say_username', models.BooleanField(default=True, help_text='พูดชื่อผู้ใช้ก่อนข้อความ (เช่น username... รอ 3 วินาที... ข้อความ)')),
                ('responder_enabled', models.BooleanField(default=True, help_text='เล่นเสียง TTS สำหรับผู้ตอบ (Character)')),
                ('responder_voice', models.CharField(default='th-TH-PremwadeeNeural', help_text='เสียง TTS สำหรับผู้ตอบ', max_length=100)),
                ('responder_rate', models.CharField(default='+0%', help_text='ความเร็วเสียงผู้ตอบ', max_length=10)),
                ('responder_delay_ms', models.IntegerField(default=3000, help_text='เวลารอระหว่างชื่อผู้ใช้กับข้อความ (มิลลิวินาที)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TTS Settings',
                'verbose_name_plural': 'TTS Settings',
            },
        ),
        migrations.CreateModel(
            name='TTSQueueItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('questioner', 'Questioner'), ('responder', 'Responder')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('playing', 'Playing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('text', models.TextField()),
                ('voice', models.CharField(default='th-TH-PremwadeeNeural', max_length=100)),
                ('rate', models.CharField(default='+0%', max_length=10)),
                ('author_name', models.CharField(blank=True, default='', max_length=100)),
                ('say_username', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, default='', help_text='e.g., youtube, chat, manual', max_length=50)),
                ('source_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('paired_item', models.ForeignKey(blank=True, help_text='Link between questioner and responder items', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paired_by', to='core.ttsqueueitem')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='core_ttsque_status_172e77_idx')],
            },
        ),
    ]
