# Generated by Django 5.2.17 on 2026-09-04 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_ttssettings_ttsqueueitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TTSQueueItem',
        ),
    ]
