# Generated by Django 6.1.1 on 2026-09-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_ttsqueueitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='avatar_border_color',
            field=models.CharField(blank=True, default='#ffffff', help_text='Hex color code for avatar border (e.g., #ff6600)', max_length=7),
        ),
    ]
