# Generated by Django 6.1.1 on 2026-09-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_character_avatar_border_color'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='core_chatme_charact_071bea_idx',
        ),
        migrations.DeleteModel(
            name='LLMProvider',
        ),
        migrations.DeleteModel(
            name='TTSSettings',
        ),
        migrations.RemoveField(
            model_name='youtubelivechatsession',
            name='character',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='character',
        ),
        migrations.DeleteModel(
            name='YouTubeChatMessage',
        ),
        migrations.DeleteModel(
            name='YouTubeLiveChatSession',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
