# Generated by Django 6.1.1 on 2026-09-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_chatmessage_core_chatme_charact_071bea_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='system_prompt',
            field=models.TextField(blank=True, default='You are a friendly AI VTuber. Respond in a casual, engaging manner.'),
        ),
    ]
