# Generated by Django 6.1.1 on 2026-09-08 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_character_system_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryMonitor',
            fields=[
            ],
            options={
                'verbose_name': 'Celery Worker Dashboard',
                'verbose_name_plural': 'Celery Worker Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.character',),
        ),
    ]
